name: yonalis.com

on:
  push:
    branches:
    - add_webpack

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: install node
    id: step_one
    run: apt install node
    - uses: actions/checkout@master
    - name: install dependancies
    id: step_two
    run: npm install
    - name: run webpack
    id: step_three
    run: npm run build
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
        SOURCE_DIR: 'dist'